Update VEH_CAN with FC messages, add IMU to legacy
macformula/can_dbc pull request #16
Opened 2024-01-19 04:52 UTC by LinF-PDX

Fix contactor feedback message, add messages for communication between FC and SG for rapid control prototyping, add messages for vehicle control diagnostics

2024-01-21 15:56 UTC, samparent97 requested changes

2024-01-21 15:56 UTC, samparent97 commented on dbcs/VEH_CAN.dbc
> +BU_: PC_SG BMS FC TMS
What is PC_SG?

2024-01-21 15:56 UTC, samparent97 commented on dbcs/legacy/CAN_FRT_controller.dbc
> +VERSION ""
What is this dbc and why is it being added in the legacy folder?

2024-01-21 18:44 UTC, LinF-PDX commented on dbcs/VEH_CAN.dbc
> +BU_: PC_SG BMS FC TMS
PC or Speedgoat

2024-01-21 18:45 UTC, LinF-PDX commented on dbcs/VEH_CAN.dbc
> +BO_ 511 FC_msg: 8 Vector__XXX
Yes

2024-01-21 18:46 UTC, LinF-PDX commented on dbcs/legacy/CAN_FRT_controller.dbc
> +VERSION ""
Old dbc for debugging control with PC and front controller, it's been merged into VEH_CAN, added to legacy folder for reference and documentation

2024-01-21 18:48 UTC, LinF-PDX commented on dbcs/legacy/CAN_GovDiag.dbc
> +BO_ 255 Gov_e_diagSts: 1 FC
This is for debugging the control system, it's an enum signal indicating the state of the governor

2024-01-26 23:32 UTC, samparent97 requested changes

2024-01-26 23:32 UTC, samparent97 commented on dbcs/VEH_CAN.dbc
> +VAL_TABLE_ gov_e_sts 7 "motor_run_error" 6 "hv_run_error" 5 "driver_interface_error" 4 "motor_startup_error" 3 "hv_startup_error" 2 "gov_running" 1 "gov_startup" 0 "gov_init" ;
Instead of `VAL_TABLE_` use `VAL_` refer to section 9.1: [DBC File Format Specification](http://mcu.so/Microcontroller/Automotive/DBC_File_Format_Documentation.pdf)

2024-01-26 23:32 UTC, samparent97 commented on dbcs/VEH_CAN.dbc
> +BO_ 1 GnssStatus: 1 CANmod
See previous comment about changing Ids for these

2024-01-26 23:32 UTC, samparent97 commented on dbcs/VEH_CAN.dbc
> +VAL_ 255 VC_govStatus 7 "motor_run_error" 6 "hv_run_error" 5 "driver_interface_error" 4 "motor_startup_error" 3 "hv_startup_error" 2 "gov_running" 1 "gov_startup" 0 "gov_init" ;
With this you should not need `VAL_TABLE_`

2024-01-26 23:33 UTC, samparent97 commented on dbcs/VEH_CAN.dbc
> +BO_ 255 VC_Status: 8 PC_SG
gov status takes 3 bits, no need for 8 bytes

2024-01-27 03:38 UTC, samparent97 commented
Merged another PR, had to rebase this one to fix merge conflicts. Functionally the same as before, just whitespace changes.

2024-02-16 03:12 UTC, LinF-PDX commented
Resolved all conversations

2024-03-03 20:19 UTC, ridasafeer reviewed
new FC messages specifically for BMS were successfully autogenerated for use on dash's updated CAN layer, can move forward with creating new dash screens dedicated for this iteration of the DBC

2024-03-21 18:23 UTC, samparent97 commented on dbcs/TEST.dbc
> +VERSION ""
What is this dbc? please provide descriptions in your PR to speed up approval process.

2024-03-21 18:23 UTC, samparent97 commented on dbcs/VEH_CAN.dbc
> + SG_ FC_ready2DriveBtn_n : 63|1@1+ (1,0) [0|1] ""  PC_SG
```suggestion
 SG_ FC_readyToDriveBtn_n : 63|1@1+ (1,0) [0|1] ""  PC_SG
```

2024-03-21 18:23 UTC, samparent97 commented on dbcs/VEH_CAN.dbc
> +BO_ 256 FC_cmd: 8 PC_SG
This is not an 8 byte message.

2024-03-21 18:23 UTC, samparent97 commented on dbcs/VEH_CAN.dbc
> +BO_ 1574 Contactor_Feedback: 3 BMS
is this change correct? Please explain. I thought we had used this message in this dbc and it worked fine

2024-03-21 23:59 UTC, LinF-PDX commented on dbcs/VEH_CAN.dbc
> +BO_ 256 FC_cmd: 8 PC_SG
Left it in 8 bytes for future proof

2024-03-22 00:00 UTC, LinF-PDX commented on dbcs/VEH_CAN.dbc
> +BO_ 1574 Contactor_Feedback: 3 BMS
The contactor feedback comes in 3 bytes, the previous one was incorrect

2024-03-25 15:52 UTC, samparent97 commented on dbcs/VEH_CAN.dbc
> +BO_ 256 FC_cmd: 8 PC_SG
This does not make a ton of sense. It should match the data being transmitted.

2024-03-25 15:52 UTC, samparent97 commented on dbcs/VEH_CAN.dbc
> + SG_ FC_readyToDriveSpkr : 1|1@1+ (1,0) [0|1] ""  FC
```suggestion
 SG_ FC_readyToDriveSpeaker : 1|1@1+ (1,0) [0|1] ""  FC
```
missed this previously

2024-03-25 15:53 UTC, samparent97 reviewed
Lets get this merged today

2024-03-25 19:16 UTC, LinF-PDX commented on dbcs/VEH_CAN.dbc
> + SG_ FC_readyToDriveSpkr : 1|1@1+ (1,0) [0|1] ""  FC
Is there a reason to use the full name instead of abbreviation even though we all know what it is for?

2024-04-02 18:16 UTC, samparent97 approved these changes

2024-04-02 18:16 UTC, merged