Add Jupyter notebook to script converter and json configuration file.
macformula/can_dbc pull request #6
Opened 2023-07-22 22:06 UTC by itshady

Resolves #1 and #2 

Using the `notebook_to_script` notebook, you can convert the `canal_parser` to a runnable python script. Also all constants are extracted into `config.json`

2023-07-22 22:39 UTC, samparent97 commented
We should stick to just the .py file. Having both results in us supporting two versions of the same code.

2023-07-22 22:49 UTC, samparent97 requested changes

2023-07-22 22:49 UTC, samparent97 commented on canalgen/canal_parser.ipynb
>    },
Get rid of this file entirely

2023-07-22 22:49 UTC, samparent97 commented on canalgen/canal_parser.py
> +json_file = "config.json"
let's not have globals, instead make all these function calls  + variable definitions within a main function

2023-07-22 22:49 UTC, samparent97 commented on canalgen/config.json
> +{
Create a `configs` folder and name the files <ecuName>.json

2023-07-22 22:49 UTC, samparent97 commented on canalgen/config.json
> +  "NODE": "BMS",
I understand this is meant to be an example but we have an off the shelf BMS which would make this confusing as we would not generate  canal_messages for this node.

2023-07-22 22:49 UTC, samparent97 commented on canalgen/config.json
> +  "IGNORED_FILES": [
Let's rename this to make it more clear
```suggestion
  "IGNORED_DBCS": [
```

2023-07-22 22:49 UTC, samparent97 commented on canalgen/config.json
> +  "MIGRATED_FILE_NAMES": "canal_messages_new",
We should not allow this option as it will not allow our code to build with imported comms_manager submodule

2023-07-22 22:49 UTC, samparent97 commented on canalgen/notebook_to_script.ipynb
> +{
Remove this file

2023-07-22 22:49 UTC, samparent97 commented on canalgen/canal_parser.py
> +def load_constants(filename):
Change name `constants` to `configs`

2023-07-23 00:11 UTC, samparent97 commented on canalgen/configs/tms.json
> -    "CAN_TMS.dbc"
Remove Ignored files (keep the field). This is generally not needed as the messages/signals call out which node is sending/receiving. what this can be useful for is adding some debug dbcs and being able to exclude them later

2023-07-23 00:17 UTC, samparent97 requested changes

2023-07-23 00:17 UTC, samparent97 commented on .gitignore
> +dbcs/generated
I get that this is for example, but I dont think it makes sense to have it in dbc/generated to begin with

2023-07-23 00:17 UTC, samparent97 commented on canalgen/configs/tms.json
> +  "MOVE_TO_LOCATION": "..\\dbcs\\generated",
```suggestion
  "MOVE_TO_LOCATION": "generated",
```

2023-07-23 00:17 UTC, samparent97 commented on canalgen/canal_parser.py
> +def main(config):
nice! could you add a quick README.md on how to set this up and what commands are needed to run?

2023-07-23 02:32 UTC, itshady commented on canalgen/canal_parser.py
> +def main(config):
yessirrr

2023-07-23 02:42 UTC, samparent97 approved these changes

2023-07-23 02:43 UTC, merged

2023-07-23 02:47 UTC, itshady commented
Resolves #2